### ISSUE TITLE
Conflict with README.md and applied license.

### ISSUE THREAD

**Issue by darklegal** [roket333/Minecraft-Everything-Random-Mod#3]
Great! I've seen that you have applied a license to your project, however this presents you with a new issue.

In your README.md file, you state that users cannot distribute your mod under any circumstances, which I presumes includes modified versions of your mod.

This creates a conflict with the license you have chosen, GNU General Public License v3. In the license terms, it states users are free to distribute this software, whether modified or unmodified.

I suggest you resolve this conflict as soon as possible.

You may find a summary of the license, and many other licenses, [here.](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

Best regards,
Matthew McColl.

(Please note that I am not a lawyer, and this is not legal advice. I am in no way liable for what you intend to do with this information.)

**Comment by roket333** [comment]
Alright, I will fix this soon
I'm probably going to end up creating my own licence for this

**Comment by darklegal** [comment]
Great to hear that! I suggest reading [this answer](
https://softwareengineering.stackexchange.com/a/171268) to the question "How can I create my own software license" first.

**Comment by roket333** [comment]
I've created the license, does it seem about right?

**Comment by darklegal** [comment]
Looks good! 👍
